name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: MC174
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      run: |
       ./trimu.ps1
