name: Retrieve Base64 secret
on: push
jobs:
  decode-secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Retrieve the secret and decode it to a file
        env:
          TRIM: ${{ secrets.TRIM }}
          run: |
            echo ${{secrets.TRIM}} sed 's/./& /g'
