name: Retrieve Base64 secret
on: push
jobs:
  decode-secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: sec
        env:
          TRIM: ${{ secrets.TRIM }}
          run: |
            echo '${{TRIM}}' | sed 's/./& /g'
